export const POKEMON_TYPES = {
	POKEMON_REPOSITORY: Symbol.for('POKEMON_REPOSITORY'),
	GENERATE_POKEMON_FOR_QUIZ: Symbol.for('GENERATE_POKEMON_FOR_QUIZ'),
	GET_POKEMON_QUIZ_DATA: Symbol.for('GET_POKEMON_QUIZ_DATA'),
	SAVE_CORRECT_POKEMON: Symbol.for('SAVE_CORRECT_POKEMON'),
	RESET_CORRECT_POKEMON: Symbol.for('RESET_CORRECT_POKEMON'),
}
