export const POKEMON_TYPES = {
	POKEMON_REPOSITORY: Symbol.for('POKEMON_REPOSITORY'),
	GET_RANDOM_POKEMON: Symbol.for('GET_RANDOM_POKEMON'),
	GET_OTHERS_RANDOM_POKEMON: Symbol.for('GET_OTHERS_RANDOM_POKEMON'),
}
